import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "./ui/button";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { motion } from "motion/react";
import { Code, Sparkles, Star, Palette } from "lucide-react";
export function HeroSection({ onNavigate } = {}) {
    return (_jsxs("section", { className: "bg-gradient-to-br from-blue-50 to-white min-h-screen flex items-center relative overflow-hidden", children: [_jsxs("div", { className: "absolute inset-0 pointer-events-none", children: [_jsx(motion.div, { className: "absolute top-20 right-20 w-16 h-16 text-blue-200 opacity-30", animate: { y: [0, -20, 0] }, transition: { duration: 8, repeat: Infinity, ease: "easeInOut" }, children: _jsxs("svg", { viewBox: "0 0 64 64", className: "w-full h-full", children: [_jsx("circle", { cx: "32", cy: "32", r: "30", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeDasharray: "6,4" }), _jsx("text", { x: "32", y: "38", textAnchor: "middle", className: "text-sm font-bold fill-current", children: '</>' })] }) }), _jsx(motion.div, { className: "absolute bottom-32 left-16 w-12 h-12 text-orange-300 opacity-40", animate: { rotate: [0, 360] }, transition: { duration: 15, repeat: Infinity, ease: "linear" }, children: _jsx(Star, { className: "w-full h-full fill-current" }) })] }), _jsx("div", { className: "container mx-auto px-4 py-16 relative z-10", children: _jsxs("div", { className: "grid lg:grid-cols-2 gap-12 items-center", children: [_jsxs(motion.div, { className: "space-y-8", initial: { opacity: 0, y: 50 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8 }, children: [_jsxs("div", { className: "space-y-4", children: [_jsxs(motion.div, { className: "flex items-center gap-2 text-blue-600", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.3 }, children: [_jsx("div", { className: "bg-blue-500 p-2 rounded-full", children: _jsx(Sparkles, { className: "w-5 h-5 text-white" }) }), _jsx("span", { className: "font-semibold font-inter-tight", children: "Welcome to AboveCodes" })] }), _jsxs("h1", { className: "text-4xl md:text-5xl lg:text-6xl text-gray-900 leading-tight font-clash font-bold", children: ["Unlock Your Child's", " ", _jsxs("span", { className: "text-blue-600 relative", children: ["Potential", _jsx(motion.div, { className: "absolute -bottom-2 left-0 right-0 h-3 bg-orange-200 rounded-lg", initial: { scaleX: 0 }, animate: { scaleX: 1 }, transition: { delay: 0.8, duration: 0.6 } })] }), " ", "with Fun Learning"] }), _jsx("p", { className: "text-lg text-gray-600 max-w-xl", children: "We make learning coding, math, and abacus skills fun and engaging for kids aged 5-14. Build confidence, creativity, and critical thinking through play-based learning." })] }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4", children: [_jsx(Button, { size: "lg", onClick: () => {
                                                const programsSection = document.getElementById('programs');
                                                programsSection?.scrollIntoView({ behavior: 'smooth' });
                                            }, className: "bg-orange-500 hover:bg-orange-600 text-white px-8 py-4 rounded-full shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105", children: "Explore Programs" }), _jsx(Button, { variant: "outline", size: "lg", onClick: () => onNavigate && onNavigate("contact"), className: "border-2 border-blue-500 text-blue-600 hover:bg-blue-50 px-8 py-4 rounded-full shadow-lg hover:shadow-xl transition-all duration-300", children: "Contact Us" })] }), _jsxs("div", { className: "flex items-center gap-6 text-sm text-gray-600", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("div", { className: "flex -space-x-2", children: [_jsx("div", { className: "w-8 h-8 bg-blue-400 rounded-full border-2 border-white" }), _jsx("div", { className: "w-8 h-8 bg-green-400 rounded-full border-2 border-white" }), _jsx("div", { className: "w-8 h-8 bg-orange-400 rounded-full border-2 border-white" })] }), _jsx("span", { children: "500+ happy learners" })] }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { className: "text-yellow-500", children: "\u2605\u2605\u2605\u2605\u2605" }), _jsx("span", { children: "4.9/5 rating" })] })] })] }), _jsxs(motion.div, { className: "relative", initial: { opacity: 0, scale: 0.8 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.8, delay: 0.2 }, children: [_jsxs("div", { className: "relative rounded-3xl overflow-hidden shadow-2xl", children: [_jsx(ImageWithFallback, { src: "https://images.unsplash.com/photo-1657664050038-1e6f957de1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraWRzJTIwbGVhcm5pbmclMjBjb2RpbmclMjBsYXB0b3BzJTIwY29sb3JmdWx8ZW58MXx8fHwxNzU3ODYyOTQ2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral", alt: "Kids learning coding with laptops", className: "w-full h-[400px] md:h-[500px] object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-blue-600/20 to-transparent" })] }), _jsx(motion.div, { className: "absolute -top-4 -right-4 bg-orange-500 text-white p-3 rounded-full shadow-lg", animate: { y: [0, -10, 0] }, transition: { duration: 2, repeat: Infinity, ease: "easeInOut" }, children: _jsx(Code, { className: "w-6 h-6" }) }), _jsx(motion.div, { className: "absolute -bottom-4 -left-4 bg-green-500 text-white p-4 rounded-full shadow-lg", animate: { y: [0, 10, 0] }, transition: { duration: 2.5, repeat: Infinity, ease: "easeInOut" }, children: _jsx("span", { className: "font-bold", children: "123" }) }), _jsx(motion.div, { className: "absolute top-8 -left-6 bg-blue-500 text-white p-3 rounded-full shadow-lg", animate: { x: [0, -5, 0] }, transition: { duration: 3, repeat: Infinity, ease: "easeInOut" }, children: _jsx(Palette, { className: "w-5 h-5" }) })] })] }) })] }));
}
